name: safe
description: Flutter Safe app

publish_to: 'none'
version: 1.0.2+{"message":"Unexpected end of JSON input"}

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  injectable: ^2.1.0
  dio: ^5.0.1
  provider: ^6.0.5
  get_it: ^7.2.0
  shared_preferences: ^2.0.18
  go_router: ^6.2.0
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.4
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
