name: Pull request

on:
  pull_request:
    branches:
      - main

jobs:
  PR:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Build DI tree
        run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - name: Test
        run: flutter test