name: 'Release'

on:
  push:
    branches:
      - 'main'
      - 'feature/versioning'

env:
  BASE_HREF: '${{ github.event.repository.name }}'

  KEYSTORE_HOST: '${{ secrets.KEYSTORE_HOST }}'
  KEYSTORE_ACCESS_TOKEN: '${{ secrets.KEYSTORE_ACCESS_TOKEN }}'

  GOOGLE_BUCKET_NAME: '${{ secrets.GOOGLE_BUCKET_NAME }}'
  GOOGLE_PRIVATE_KEY_PASSWORD: '${{ secrets.GOOGLE_PRIVATE_KEY_PASSWORD }}'
  GOOGLE_SERVICE_ACCOUNT: '${{ secrets.GOOGLE_SERVICE_ACCOUNT }}'
  GOOGLE_BUILD_NUMBER_FILE: '${{ secrets.GOOGLE_BUILD_NUMBER_FILE }}'

  DEPLOY_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

jobs:
  Prebuild:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'write'

    steps:
      - name: 'Load code'
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 2
      - name: 'Setup Flutter'
        uses: 'subosito/flutter-action@v2'
        with:
          channel: 'stable'
      - name: 'Declare environment variables'
        run: 'chmod +x scripts/helpers/declare_env_variables.sh && scripts/helpers/declare_env_variables.sh'
      - name: 'Build'
        run: 'chmod +x scripts/flutter/build.sh && scripts/flutter/build.sh'
      - name: 'Upload version data'
        uses: 'actions/upload-artifact@v3'
        with:
          name: 'Version'
          path: '${{ env.DIST_FOLDER }}'
          retention-days: 1

  Web:
    runs-on: 'ubuntu-latest'

    needs:
      - 'Prebuild'

    permissions:
      contents: 'write'
      id-token: 'write'

    steps:
      - name: 'Load code'
        uses: 'actions/checkout@v3'
      - name: 'Setup Flutter'
        uses: 'subosito/flutter-action@v2'
        with:
          channel: 'stable'
      - name: 'Declare environment variables'
        run: 'chmod +x scripts/helpers/declare_env_variables.sh && scripts/helpers/declare_env_variables.sh'
      - name: 'Prebuild'
        run: 'chmod +x scripts/flutter/prebuild.sh && scripts/flutter/prebuild.sh'
      - name: 'Build'
        run: 'chmod +x scripts/web/build.sh && scripts/web/build.sh'
      - name: 'Deploy web version'
        uses: 'peaceiris/actions-gh-pages@v3'
        with:
          github_token: '${{ env.DEPLOY_TOKEN }}'
          folder: '${{ env.DIST_FOLDER }}/web'

  Android:
    runs-on: 'ubuntu-latest'
    needs:
      - 'Prebuild'

    steps:
      - name: 'Load code'
        uses: 'actions/checkout@v3'
      - name: 'Setup Flutter'
        uses: 'subosito/flutter-action@v2'
        with:
          channel: 'stable'
      - name: 'Setup Java'
        uses: 'actions/setup-java@v2'
        with:
          distribution: 'zulu'
          java-version: 18
      - name: 'Declare environment variables'
        run: 'chmod +x scripts/helpers/declare_env_variables.sh && scripts/helpers/declare_env_variables.sh'
      - name: 'Prebuild'
        run: 'chmod +x scripts/flutter/prebuild.sh && scripts/flutter/prebuild.sh'
      - name: 'Build'
        run: 'chmod +x scripts/android/build.sh && scripts/android/build.sh'
      - name: 'Upload android bundle'
        uses: 'actions/upload-artifact@v3'
        with:
          name: 'Android'
          path: '${{ env.DIST_FOLDER }}/android'
          retention-days: 1

  Release:
    runs-on: 'ubuntu-latest'
    needs:
      - 'Web'
      - 'Android'

    steps:
      - name: 'Load version data'
        uses: 'actions/download-artifact@v3'
        with:
          name: 'Version'
      - name: 'Get release tag'
        run: 'echo "RELEASE_TAG=$(<version.txt)" >> $GITHUB_ENV'
      - name: 'Load Android bundle'
        uses: 'actions/download-artifact@v3'
        with:
          name: 'Android'
          path: '${{ env.DIST_FOLDER }}'
      - name: 'Create release'
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ env.DEPLOY_TOKEN }}'
          automatic_release_tag: '${{ env.RELEASE_TAG }}'
          prerelease: false
          files: '${{ env.DIST_FOLDER }}/**/*'
