name: Release

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  APP_NAME: 'safe'
  FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
  FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}

jobs:
  Web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Build web version
        run: |
          chmod +x ./scripts/build_web.sh
          ./scripts/build_web.sh ${{ github.event.repository.name }}
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_WEB_API_KEY }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_WEB_APP_ID }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      - name: Deploy web version
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist

  Android:
    runs-on: ubuntu-latest

    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      RELEASE_SIGN_KEY_ALIAS: ${{ secrets.RELEASE_SIGN_KEY_ALIAS }}
      RELEASE_SIGN_KEY_PASSWORD: ${{ secrets.RELEASE_SIGN_KEY_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 18
      - name: Checkout keystore repo
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.KEYSTORE_GIT_REPOSITORY }}
          token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
          path: frontend/android/app/keystore
      - name: Get git tag
        uses: olegtarasov/get-tag@v2.1
      - name: Check tag
        if: ${{ env.GIT_TAG_NAME == '' }}
        run: echo "GIT_TAG_NAME=latest" >> $GITHUB_ENV
      - name: Build android version
        run: |
          chmod +x ./scripts/build_android.sh
          ./scripts/build_android.sh $APP_NAME-$GIT_TAG_NAME
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_ANDROID_API_KEY }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Android
          path: dist/*
          retention-days: 1

  Release:
    runs-on: ubuntu-latest
    needs:
      - Web
      - Android

    steps:
      - name: Get git tag
        uses: olegtarasov/get-tag@v2.1
      - name: Check tag
        if: ${{ env.GIT_TAG_NAME == '' }}
        run: echo "GIT_TAG_NAME=latest" >> $GITHUB_ENV
      - name: Download all artifacts
        uses: actions/download-artifact@v3
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ env.GIT_TAG_NAME }}
          prerelease: false
          files: '**/*'